spring:
  datasource:
    url: jdbc:postgresql://150.136.243.102:5432/stdeals
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

scheduler:
  deals:
    enabled: false
    cron: "0 0 */12 * * *"

deals:
  default-sync-status: ACTIVE

app:
  base-url: http://157.151.212.233:5173
  jwt-secret: 431f3c15ab3acd2e034fa3df7f6a370adb3ace2f32685affa934b79cd2a896f4
  jwt-expiration-ms: 86400000
  cors:
    allowed-origins: http://157.151.212.233:5173

image-upload:
  url: https://dealsoftweek.com/api/internal/images/upload
  api-key: 3896ce9644b0719552390bae80062b0cbb27755d8c33c1343b52ea7a90c6d330